name: keeper
description: "App that is designed to help organize multiple items"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_bloc: ^8.1.6
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  collection: ^1.18.0
  easy_localization: ^3.0.7
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.5
  path: ^1.9.0
  get_it: ^8.0.2
  fpdart: ^1.1.1
  window_manager: ^0.4.3
  desktop_window: ^0.4.2
  windows_notification: ^1.3.0
  flutter_local_notifications: ^18.0.1
  file_picker: ^8.1.6

dev_dependencies:
  flutter_lints: ^4.0.0
  drift_dev: ^2.22.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true